apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.HOME_ZONE
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - spec.hostnames.0
        options:
          delimiter: '.'
          index: 1

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.S3_ENDPOINT
    targets:
      - select:
          kind: ObjectStore
        fieldPaths:
          - spec.configuration.endpointURL

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.S3_BACKUP_BUCKET
    targets:
      - select:
          kind: ObjectStore
        fieldPaths:
          - spec.configuration.destinationPath
        options:
          delimiter: '/'
          index: 2

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.EGRESS_GATEWAY
    targets:
      - select:
          kind: Deployment
          labelSelector: egress=vpn
        fieldPaths:
          - spec.template.metadata.annotations.k8s\.v1\.cni\.cncf\.io/networks
        options:
          delimiter: '"'
          index: 7
      - select:
          kind: NetworkAttachmentDefinition
          name: vpn-egress
        fieldPaths:
          - spec.config
        options:
          delimiter: '"'
          index: 43

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.EGRESS_SUBNET
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: vpn-egress
        fieldPaths:
          - spec.config
        options:
          delimiter: '"'
          index: 31

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.EGRESS_POD_RANGE
      options:
        delimiter: '-'
        index: 0
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: vpn-egress
        fieldPaths:
          - spec.config
        options:
          delimiter: '"'
          index: 35

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.EGRESS_POD_RANGE
      options:
        delimiter: '-'
        index: 1
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: vpn-egress
        fieldPaths:
          - spec.config
        options:
          delimiter: '"'
          index: 39

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.DNS_SERVERS
      options:
        delimiter: ','
        index: 0
    targets:
      - select:
          kind: Deployment
          labelSelector: egress=vpn
        fieldPaths:
          - spec.template.spec.dnsConfig.nameservers.0

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.DNS_SERVERS
      options:
        delimiter: ','
        index: 1
    targets:
      - select:
          kind: Deployment
          labelSelector: egress=vpn
        fieldPaths:
          - spec.template.spec.dnsConfig.nameservers.1

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_HOST
    targets:
      - select:
          kind: Deployment
          labelSelector: nas-apps=true
        fieldPaths:
          - spec.template.spec.volumes.[name=apps].nfs.server

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_APPS_PATH
    targets:
      - select:
          kind: Deployment
          labelSelector: nas-apps=true
        fieldPaths:
          - spec.template.spec.volumes.[name=apps].nfs.path

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_HOST
    targets:
      - select:
          kind: Deployment
          labelSelector: share=media
        fieldPaths:
          - spec.template.spec.volumes.[name=media].nfs.server

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_MEDIA_PATH
    targets:
      - select:
          kind: Deployment
          labelSelector: share=media
        fieldPaths:
          - spec.template.spec.volumes.[name=media].nfs.path

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_HOST
    targets:
      - select:
          kind: Deployment
          labelSelector: share=library
        fieldPaths:
          - spec.template.spec.volumes.[name=library].nfs.server

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_PHOTOS_PATH
    targets:
      - select:
          kind: Deployment
          labelSelector: share=library
        fieldPaths:
          - spec.template.spec.volumes.[name=library].nfs.path

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_HOST
    targets:
      - select:
          kind: Deployment
          labelSelector: share=knowledge
        fieldPaths:
          - spec.template.spec.volumes.[name=knowledge].nfs.server

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_KNOWLEDGE_PATH
    targets:
      - select:
          kind: Deployment
          labelSelector: share=knowledge
        fieldPaths:
          - spec.template.spec.volumes.[name=knowledge].nfs.path

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_HOST
    targets:
      - select:
          kind: Deployment
          labelSelector: share=emby
        fieldPaths:
          - spec.template.spec.volumes.[name=emby].nfs.server

  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.NAS_EMBY_PATH
    targets:
      - select:
          kind: Deployment
          labelSelector: share=emby
        fieldPaths:
          - spec.template.spec.volumes.[name=emby].nfs.path
