apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://placeholder/postgres
    endpointURL: placeholder
    s3Credentials:
      accessKeyId:
        name: s3
        key: access-key
      secretAccessKey:
        name: s3
        key: secret-key
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3

  postgresql:
    shared_preload_libraries:
      - vchord.so

  storage:
    storageClass: database
    size: 40Gi

  bootstrap:
    recovery:
      source: backup

  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: postgres
          serverName: postgres

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres
        serverName: postgres

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-db
      - name: paperless
        ensure: present
        login: true
        passwordSecret:
          name: paperless-db

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
spec:
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  cluster:
    name: postgres
  name: immich
  owner: immich
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: paperless
spec:
  cluster:
    name: postgres
  name: paperless
  owner: paperless
