apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: paperless
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-db
        property: paperless
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: home-misc
        property: paperless-secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: karakeep
    creationPolicy: Owner
  data:
    - secretKey: meilisearch-master-key
      remoteRef:
        key: home-misc
        property: meilisearch-master-key
    - secretKey: nextauth-secret
      remoteRef:
        key: home-misc
        property: karakeep-nextauth-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: couchdb
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: obsidian
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-misc
        property: couchdb-password
