apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: paperless
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-db
        property: paperless
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: home-misc
        property: paperless-secret-key
    - secretKey: admin-password
      remoteRef:
        key: home-misc
        property: paperless-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-r2
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless-r2
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RCLONE_CONFIG_R2_ACCESS_KEY_ID: "{{ .accessKeyId }}"
        RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
        RCLONE_CONFIG_R2_ENDPOINT: "https://{{ .accountId }}.r2.cloudflarestorage.com"
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: home-misc
        property: paperless-r2-access-key-id
    - secretKey: secretAccessKey
      remoteRef:
        key: home-misc
        property: paperless-r2-secret-access-key
    - secretKey: accountId
      remoteRef:
        key: home-misc
        property: cloudflare-account-id
