apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../config
  - secrets.yaml
  - plex.yaml
  - emby.yaml
  - sonarr.yaml
  - radarr.yaml
  - prowlarr.yaml
  - bazarr.yaml
  - overseerr.yaml
  - transmission.yaml
components:
  - ../../components/cluster-values
