apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn-egress
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vpn-egress",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [[{
          "subnet": "10.7.123.0/24",
          "rangeStart": "10.7.123.80",
          "rangeEnd": "10.7.123.90",
          "gateway": "10.7.123.1"
        }]]
      }
    }
