apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: meilisearch
    creationPolicy: Owner
  data:
    - secretKey: master-key
      remoteRef:
        key: home-misc
        property: meilisearch-master-key
