apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: s3
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: immich-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: immich
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-db
        property: immich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: paperless-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: paperless
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-db
        property: paperless
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: meilisearch
    creationPolicy: Owner
  data:
    - secretKey: master-key
      remoteRef:
        key: home-misc
        property: meilisearch-master-key
