apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: plex
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: plex
