apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: immich-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: immich
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: home-db
        property: immich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: immichframe
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: home-misc
        property: immichframe-api-key
