apiVersion: v1
kind: ConfigMap
metadata:
  name: home-config
data:
  TZ: UTC
  HOME_ZONE: svc.k8s.shokugami.place

  NAS_HOST: 10.11.7.30
  NAS_MEDIA_PATH: /mnt/main/media
  NAS_PHOTOS_PATH: /mnt/main/usr/immich/upload
  NAS_KNOWLEDGE_PATH: /mnt/main/svc/knowledge
  NAS_EMBY_PATH: /mnt/main/usr/emby
  NAS_APPS_PATH: /mnt/main/k8s/apps

  S3_ENDPOINT: http://10.11.7.30:30292
  S3_BACKUP_BUCKET: backups

  LLM_ENDPOINT: http://10.11.7.11:11434
  EGRESS_GATEWAY: 10.7.123.1
  EGRESS_SUBNET: 10.7.123.0/24
  EGRESS_POD_RANGE: 10.7.123.80-10.7.123.90
  DNS_SERVERS: 1.1.1.1,1.0.0.1

