apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../config
  - secrets.yaml
  - audiobookshelf.yaml
  - paperless.yaml
  - karakeep.yaml
  - obsidian-livesync.yaml
components:
  - ../../components/cluster-values

replacements:
  - source:
      kind: ConfigMap
      name: home-config
      fieldPath: data.HOME_ZONE
    targets:
      - select:
          kind: Deployment
          name: paperless
        fieldPaths:
          - spec.template.spec.containers.[name=paperless].env.[name=PAPERLESS_URL].value
        options:
          delimiter: '.'
          index: 1
      - select:
          kind: Deployment
          name: karakeep
        fieldPaths:
          - spec.template.spec.containers.[name=karakeep].env.[name=NEXTAUTH_URL].value
        options:
          delimiter: '.'
          index: 1
